DROP TABLE IF EXISTS order_detail CASECADE;
CREATE TABLE order_detail (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 0
);

